// Sugestões de "DESPESA - CLASSIFICAÇÃO" extraídas do histórico real de
// prestação de contas (planilha CAIXA) — é só uma lista de apoio pro
// autocomplete do campo, não trava o usuário: ele pode digitar qualquer coisa.
export const CATEGORIAS_SUGERIDAS = [
  'ABASTECIMENTO', 'ACESSORIO MOTO', 'ADAPTADOR', 'AJUSTE ROUPA', 'ALIMENTAÇÃO', 'ALMOÇO',
  'BALSA', 'BATERIA', 'BAU MOTO', 'BORRACHARIA', 'BROCA', 'CABO', 'CABO CARGA', 'CABO TIPO C',
  'CADEADO', 'CAFÉ DA MANHÃ', 'CAMARA DE AR', 'CANIVET', 'CARGA BATERIA', 'CARREGADOR', 'CHAVE',
  'COFFEE BREAK', 'COMPRA', 'CONSERTO', 'CONSERTO CELULAR', 'CONSERTO MOTO', 'CONSERTO PNEU',
  'CORREIOS', 'COSTURA', 'DADOS MOVEIS', 'EMPLACAMENTO', 'ENSAIO ELETRCICO', 'EPC', 'EPI',
  'EVENTO SIPAT', 'FAIXA DE SINALIZAÇÃO', 'GELO', 'JANTAR', 'LANCHE', 'LAVA JATO', 'LAVAGEM',
  'LAVAGEM DE VIATURA', 'LED', 'LIMPEZA BASE', 'LUVA', 'MANUTENÇÃO', 'MATERIAIS',
  'MATERIAL DE CONSTRUÇÃO', 'MATERIAL REPARO', 'MOLA', 'OLEO', 'PARAFUSOS', 'PASSAGEM', 'PLACA',
  'PREMIAÇÃO', 'PREMIAÇÃO EQUIPES', 'PRODUTO PARA VEÍCULO', 'RECARGA DADOS', 'REFEIÇÃO',
  'REMENDO', 'REMENDO PNEU', 'RESISTENCIA', 'SERRA COPO', 'SERVIDOR', 'SERVIÇO BATERIA',
  'SERVIÇO PNEU', 'SERVIÇO VIATURA', 'SISTEMA', 'SOLDA', 'SUPORTE TV', 'TELEFONIA', 'TONER',
  'TROCA BATERIA', 'TROFEU ACRÍLICO', 'VIAGEM', 'VULCANIZAÇÃO', 'VULCANIZAÇÃO PNEU', 'ÁGUA',
]

export const FORMAS_PAGAMENTO = ['PIX', 'Dinheiro', 'Cartão', 'Transferência']

export const TIPOS_COMPROVANTE = ['Recibo', 'Nota Fiscal', 'Extrato Conta', 'Outro']
