-- Aplicar em ambos schemas: dev e public via Codex
--
-- Suporte à importação em lote de "Abertura de Ocorrência" a partir de
-- planilha (TOA). Linhas que não conseguem resolver o supervisor de campo
-- (via matrícula em estrutura_equipes -> usuarios) ficam guardadas aqui —
-- NÃO viram uma `ocorrencia` até o usuário corrigir manualmente ou excluir.

-- DESENVOLVIMENTO ─────────────────────────────────────────────────────────────

create table if not exists dev.ocorrencias_importacao_pendentes (
  id                        bigint generated by default as identity primary key,
  prefixo                   text,
  uc                        text,
  os                        text,
  registro_exec             text,
  data_conclusao_raw        text,
  data_conclusao            text,
  tipo_conclusao            text,
  descricao                 text,
  colaborador_1             text,
  colaborador_2             text,
  direcionado_para          text,
  matricula_fiscal_destino  text,
  motivo_pendencia          text,
  criado_por                text,
  criado_em                 timestamptz not null default now()
);

alter table dev.ocorrencias_importacao_pendentes disable row level security;
grant all on dev.ocorrencias_importacao_pendentes to anon, authenticated;
grant usage, select on dev.ocorrencias_importacao_pendentes_id_seq to anon, authenticated;

-- PRODUCAO ────────────────────────────────────────────────────────────────────

create table if not exists public.ocorrencias_importacao_pendentes (
  id                        bigint generated by default as identity primary key,
  prefixo                   text,
  uc                        text,
  os                        text,
  registro_exec             text,
  data_conclusao_raw        text,
  data_conclusao            text,
  tipo_conclusao            text,
  descricao                 text,
  colaborador_1             text,
  colaborador_2             text,
  direcionado_para          text,
  matricula_fiscal_destino  text,
  motivo_pendencia          text,
  criado_por                text,
  criado_em                 timestamptz not null default now()
);

alter table public.ocorrencias_importacao_pendentes disable row level security;
grant all on public.ocorrencias_importacao_pendentes to anon, authenticated;
grant usage, select on public.ocorrencias_importacao_pendentes_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
